# Change these first
owner: landra-sistemas # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Landra Website
    url: https://www.landrasistemas.es
    icon: https://dash.landrasoftware.com/data/userTabs/favicon.png
  - name: Dashboard
    url: https://dash.landrasoftware.com
  - name: Telf. Guardia Landra
    url: https://integration.landrasoftware.com/GuardiaLandra
    icon: https://dash.landrasoftware.com/data/userTabs/favicon.png
  - name: Telf. Guardia Abbot
    url: https://integration.landrasoftware.com/GuardiaAbbott
    icon: https://dash.landrasoftware.com/data/userTabs/favicon.png

assignees:
  - thorin8k

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://dash.landrasoftware.com/data/userTabs/Icono_Landra_invertido_500x500.png
  name: Landra Upptime
  introTitle: "**Landra Upptime** monitorización de sitios importantes."
  introMessage: Los siguientes endpoints se encuentran monitorizados mediante Github. El sistema gestionará automáticamente las Alertas de inactividad y los tiempos de respuesta de cada uno de ellos.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
